version: '3'
services:
  client:
    container_name: primary_bid_client
    restart: always
    build: ./client
    ports:
      - '3006:3006'
      
  server:
    container_name: primary_bid_server
    restart: always
    build: ./server
    ports:
      - '3000:3000'